version: "3.8"
services:
  backend:
    build: ./Backend
    ports:
      - 5000:5000
    environment:
      - PORT = 5000
      - NODE_ENV = development
      - MONGO_URI = mongodb+srv://dentist:dentist@dentist.fwkvdfn.mongodb.net/DentistDatabase?retryWrites=true&w=majority
      - JWT_SECRET = asdfjkl;;lkjfdsa
      - JWT_EXPIRE = 30d
      - JWT_COOKIE_EXPIRE = 30
      - HOST= http://localhost:5000
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET='asdfjkl;;lkjfdsa'